export const NormalOpNormChemicalColumns = [
  {
    field: 'Particulars',
    title: 'Type',
    widthT: 220,
    groupable: true,
    editable: false,
    hidden: true,
  },
  {
    field: 'materialFkId',
    title: 'Particulars',
    width: 120,
    hidden: true,
    minWidth: 120,
  },
  {
    field: 'sapCode',
    title: 'Sap Mat Code',
    width: 130,
    minWidth: 100,
  },
  {
    field: 'productName',
    title: 'Particulars',
    widthT: 130,
    minWidth: 100,
  },

  {
    field: 'UOM',
    title: 'UOM / MT',
    widthT: 60,
    editable: false,
    minWidth: 100,
  },

  {
    field: 'april',
    title: 4,
    editable: true,
    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'may',
    title: 5,
    editable: true,

    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'june',
    title: 6,
    editable: true,

    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'july',
    title: 7,
    editable: true,

    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },

  {
    field: 'august',
    title: 8,
    editable: true,

    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'september',
    title: 9,
    editable: true,

    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'october',
    title: 10,
    editable: true,

    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'november',
    title: 11,
    editable: true,

    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'december',
    title: 12,
    editable: true,
    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'january',
    title: 1,
    editable: true,
    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'february',
    title: 2,
    editable: true,
    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'march',
    title: 3,
    editable: true,
    width: 120,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'wtAverage',
    title: 'Weighted Average',
    width: 120,
    editable: false,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'remarks',
    title: 'Remark',
    widthT: 80,
    editable: true,
    minWidth: 100,
  },

  {
    field: 'idFromApi',
    title: 'idFromApi',
    hidden: true,
    minWidth: 100,
  },
  {
    field: 'isEditable',
    title: 'isEditable',
    hidden: true,
    minWidth: 100,
  },
]
