export const BusinessDemandMegColumns = [
  {
    field: 'Particulars',
    title: 'Type',
    width: 100,
    groupable: true,
    headerClass: 'bold-header',
    filterable: 'false',
    editable: false,
    hidden: true,
    isVisible: false
  },
  {
    field: 'normParameterId',
    title: 'Particulars',
    editable: false,
    width: 150,
    hidden: true,
    isVisible: false
  },
  {
    field: 'displayName',
    title: 'Particulars',
    editable: false,
    widthT: 150,
    minWidth: 120,
  },
  {
    field: 'UOM',
    title: 'UOM',
    editable: false,
    widthT: 80,
    minWidth: 100,
  },
  {
    field: 'april',
    title: 4,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'may',
    title: 5,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'june',
    title: 6,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'july',
    title: 7,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'aug',
    title: 8,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'sep',
    title: 9,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },

  {
    field: 'oct',
    title: 10,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'nov',
    title: 11,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'dec',
    title: 12,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'jan',
    title: 1,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'feb',
    title: 2,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'march',
    title: 3,
    editable: true,
    width: 50,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'remark',
    title: 'Remark',
    editable: false,
    widthT: 50,
    type: 'string',
    minWidth: 100
  },
  {
    field: 'idFromApi',
    title: 'idFromApi',
    filterable: 'false',
    hidden: true,
    isVisible: false,
    minWidth: 100
  },
]

export const SlowDownMegColumns = [
  {
    field: 'discription',
    title: 'Slowdown Desc',
    editable: true,
    type: 'descLimit',
    widthT: 230,
    autoAdjust: false,
    minWidth: 200,
  },

  {
    field: 'maintenanceId',
    title: 'maintenanceId',
    editable: false,
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },

  {
    field: 'maintStartDateTime',
    title: 'SD- From',
    type: 'dateTime',
    editable: true,
    widthT: 120,
    minWidth: 100,
  },

  {
    field: 'maintEndDateTime',
    title: 'SD- To',
    type: 'dateTime',
    editable: true,
    widthT: 120,
    minWidth: 100,
  },

  {
    field: 'durationInHrs',
    title: 'Duration (hrs)',
    editable: true,
    widthT: 100,
    minWidth: 100,
  },

  {
    field: 'rateEOE',
    title: 'EOE Production Rate',
    editable: true,
    type: 'number',
    widthT: 100,
    minWidth: 100,
  },
  {
    field: 'rateEO',
    title: 'EO Production Rate',
    editable: true,
    type: 'number',
    widthT: 100,
    minWidth: 100,
  },

  {
    field: 'remark',
    title: 'Remarks',
    editable: true,
    widthT: 200,
    autoAdjust: false,
    minWidth: 100,
  },
]

export const NormalOpNormMegColumns = [
  {
    field: 'Particulars',
    title: 'Type',
    widthT: 100,
    groupable: true,
    editable: false,
    hidden: true,
    minWidth: 120,
    isVisible: false,
  },
  {
    field: 'materialFkId',
    title: 'Particulars',
    width: 100,
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
  {
    field: 'productName',
    title: 'Particulars',
    widthT: 120,
    minWidth: 120,
  },

  {
    field: 'UOM',
    title: 'UOM/MT',
    widthT: 80,
    editable: false,
    minWidth: 100,
  },

  {
    field: 'april',
    title: 4,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'may',
    title: 5,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'june',
    title: 6,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'july',
    title: 7,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },

  {
    field: 'august',
    title: 8,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'september',
    title: 9,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'october',
    title: 10,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'november',
    title: 11,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'december',
    title: 12,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'january',
    title: 1,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'february',
    title: 2,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'march',
    title: 3,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'negativeNumber',
    minWidth: 100,
  },
  {
    field: 'remarks',
    title: 'Remark',
    widthT: 80,
    editable: true,
    minWidth: 100,
  },

  {
    field: 'idFromApi',
    title: 'idFromApi',
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
  {
    field: 'isEditable',
    title: 'isEditable',
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
]
export const CrackerColums = [
  {
    field: 'Particulars',
    title: 'Type',
    widthT: 100,
    groupable: true,
    editable: false,
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
  {
    widthT: 100,
    columnType: 'checkbox',
    minWidth: 100,
  },
  {
    field: 'materialFkId',
    title: 'Particulars',
    width: 100,
    hidden: true,
    minWidth: 100,
  },
  {
    field: 'productName',
    title: 'Particulars',
    widthT: 120,
    minWidth: 120,
  },

  {
    field: 'UOM',
    title: 'UOM / MT',
    widthT: 90,
    editable: false,
    minWidth: 100,
  },

  {
    field: 'april',
    title: 4,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'may',
    title: 5,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'june',
    title: 6,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'july',
    title: 7,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },

  {
    field: 'august',
    title: 8,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'september',
    title: 9,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'october',
    title: 10,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'november',
    title: 11,
    editable: true,

    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'december',
    title: 12,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'january',
    title: 1,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'february',
    title: 2,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'march',
    title: 3,
    editable: true,
    width: 100,
    align: 'right',
    format: '{0:#.###}',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'remarks',
    title: 'Remark',
    widthT: 100,
    editable: true,
    minWidth: 100,
  },

  {
    field: 'idFromApi',
    title: 'idFromApi',
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
  {
    field: 'isEditable',
    title: 'isEditable',
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
]

export const ShutdownConsumptionMegColumns = [
  {
    field: 'Particulars',
    headerName: 'Type',
    width: 100,
    hidden: true,
    minWidth: 120,
    isVisible: false,
  },
  {
    field: 'materialFkId',
    headerName: 'Particulars',
    minWidth: 120,
    editable: false,
    hidden: true,
    width: 120,
    isVisible: false,
  },
  {
    field: 'productName',
    headerName: 'Particulars',
    widthT: 120,
    editable: false,
    minWidth: 120,
  },
  {
    field: 'UOM',
    headerName: 'UOM',
    widthT: 80,
    editable: false,
    minWidth: 100,
  },

  ...Array.from({ length: 12 }, (_, i) => {
    const monthIndex = (i + 4) % 12 || 12
    const monthField = new Date(2000, monthIndex - 1)
      .toLocaleString('en-US', { month: 'long' })
      .toLowerCase()

    return {
      field: monthField,
      width: 100,
      type: 'negativeNumber',
      format: '{0:#.###}',
      editable: false,
      isDisabled: true,
      monthNumber: monthIndex,
      minWidth: 100,
    }
  }),

  {
    field: 'remarks',
    headerName: 'Remark',
    // widthT: 160,
    editable: false,
    minWidth: 100,
  },
  {
    field: 'idFromApi',
    headerName: 'idFromApi',
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
]

export const SlowdownNormsMegColumns = [
  {
    field: 'Particulars',
    headerName: 'Type',
    width: 100,
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
  {
    field: 'materialFkId',
    headerName: 'Particulars',
    minWidth: 150,
    editable: false,
    hidden: true,
    width: 100,
    isVisible: false,
  },
  {
    field: 'productName',
    headerName: 'Particulars',
    widthT: 120,
    editable: false,
    minWidth: 120,
  },
  {
    field: 'UOM',
    headerName: 'UOM',
    widthT: 80,
    editable: false,
    minWidth: 100,
  },

  ...Array.from({ length: 12 }, (_, i) => {
    const monthIndex = (i + 4) % 12 || 12
    const monthField = new Date(2000, monthIndex - 1)
      .toLocaleString('en-US', { month: 'long' })
      .toLowerCase()

    return {
      field: monthField,
      width: 100,
      type: 'number',
      format: '{0:#.###}',
      editable: false,
      isDisabled: true,
      monthNumber: monthIndex,
      minWidth: 100,
    }
  }),

  {
    field: 'remarks',
    headerName: 'Remark',
    widthT: 100,
    editable: false,
    minWidth: 100,
  },
  {
    field: 'idFromApi',
    headerName: 'idFromApi',
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
]

export const ConsumptionAopMegColumns = [
  {
    field: 'Particulars',
    title: 'Type',
    editable: false,
    width: 100,
    hidden: true,
    minWidth: 150,
    isVisible: false,
  },
  {
    field: 'NormParametersId',
    hidden: true,
    minWidth: 150,
    isVisible: false,
  },

  {
    field: 'productName',
    title: 'Particulars',
    editable: false,
    widthT: 120,
    minWidth: 150,
  },
  {
    field: 'UOM',
    title: 'UOM/MT',
    editable: false,
    widthT: 90,
    minWidth: 150,
  },
  {
    field: 'april',
    title: 4,
    minWidth: 100,
  },
  {
    field: 'may',
    title: 5,
    minWidth: 100,
  },
  {
    field: 'june',
    title: 6,
    minWidth: 100,
  },
  {
    field: 'july',
    title: 7,
    minWidth: 100,
  },
  {
    field: 'aug',
    title: 8,
    minWidth: 100,
  },
  {
    field: 'sep',
    title: 9,
    minWidth: 100,
  },
  {
    field: 'oct',
    title: 10,
    minWidth: 100,
  },
  {
    field: 'nov',
    title: 11,
    minWidth: 100,
  },
  {
    field: 'dec',
    title: 12,
    minWidth: 100,
  },
  {
    field: 'jan',
    title: 1,
    minWidth: 100,
  },
  {
    field: 'feb',
    title: 2,
    minWidth: 100,
  },
  {
    field: 'march',
    title: 3,
    minWidth: 100,
  },
  {
    field: 'isEditable',
    title: 'isEditable',
    hidden: true,
    minWidth: 100,
    isVisible: false,
  },
]
