export const BusinessDemandPetColumns = [
  {
    field: 'Particulars',
    title: 'Type',
    width: 100,
    groupable: true,
    headerClass: 'bold-header',
    filterable: 'false',
    editable: false,
    hidden: true,
    isVisible: false,
    minWidth: 100,
  },
  {
    field: 'normParameterId',
    title: 'Particulars',
    editable: false,
    width: 100,
    hidden: true,
    isVisible: false,
    minWidth: 100,
  },
  {
    field: 'displayName',
    title: 'Particulars',
    editable: false,
    widthT: 120,
    minWidth: 100,
  },
  {
    field: 'UOM',
    title: 'UOM',
    editable: false,
    widthT: 80,
    minWidth: 80,
  },
  {
    field: 'april',
    title: 4,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'may',
    title: 5,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'june',
    title: 6,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'july',
    title: 7,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'aug',
    title: 8,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'sep',
    title: 9,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },

  {
    field: 'oct',
    title: 10,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'nov',
    title: 11,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'dec',
    title: 12,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'jan',
    title: 1,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'feb',
    title: 2,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'march',
    title: 3,
    editable: true,
    width: 100,
    align: 'left',
    headerAlign: 'left',
    type: 'number',
    minWidth: 100,
  },
  {
    field: 'remark',
    title: 'Remark',
    editable: false,
    widthT: 100,
    type: 'string',
    minWidth: 100,
  },
  {
    field: 'idFromApi',
    title: 'idFromApi',
    filterable: 'false',
    hidden: true,
    isVisible: false,
  },
]
