const getSiteAOPReportColumns = ({ AOP_YEAR, valueFormat, prev, next }) => ({
  siteTeam: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No.',
      editable: false,
      align: 'right',
      format: '{0:0}',
      widthT: 60,
    },
    { field: 'jobRole', title: 'Job Role', editable: false, widthT: 150 },
    { field: 'name', title: 'Name', editable: true, widthT: 150 },
    { field: 'age', title: 'Age', editable: true, type: 'number', widthT: 150 },
    {
      field: 'teamSize',
      title: 'Team Size',
      editable: true,
      type: 'number',
      widthT: 150,
    },
    { field: 'remark', title: 'Remark', widthT: 150, editable: true },
  ],
  safetyPerformance: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.no',
      widthT: 58,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'uom', title: 'UOM', widthT: 80, editable: false },
    {
      field: 'bestAchieved',
      title: 'Best Achieved',
      format: valueFormat,
      type: 'number',
      editable: true,
    },
    {
      title: `FY ${AOP_YEAR}`,
      children: [
        {
          field: 'aop',
          title: 'AOP',
          editable: true,
          align: 'right',
          format: valueFormat,
          type: 'number',
        },
        {
          field: 'actual',
          title: 'Actual',
          editable: true,
          align: 'right',
          format: valueFormat,
          type: 'number',
        },
      ],
    },
    { field: 'remark', title: 'Remarks', widthT: 100, editable: true },
  ],
  majorIncidents: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No.',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'plant', title: 'Plant', widthT: 100, editable: true },
    {
      field: 'incidentDescription',
      title: 'Incident Description',
      widthT: 100,
      editable: true,
    },
    { field: 'rootCauses', title: 'Root Causes', widthT: 100, editable: true },
    {
      field: 'recommendation',
      title: 'Recommendation',
      widthT: 100,
      editable: true,
    },
    {
      field: 'targetDate',
      title: 'Target Date',
      widthT: 100,
      editable: true,
      type: 'date',
    },
    { field: 'resp', title: 'Resp.', widthT: 100, editable: true },
    { field: 'remark', title: 'Remarks', widthT: 100, editable: true },
  ],
  majorSafetyInitiative: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No.',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'plant', title: 'Plant', widthT: 100, editable: false },
    {
      field: 'initiativeDescription',
      title: 'Initiative Description',
      widthT: 100,
      editable: true,
    },
    { field: 'category', title: 'Category', widthT: 100, editable: true },
    { field: 'outcome', title: 'Outcome', widthT: 100, editable: true },
    {
      field: 'recommendation',
      title: 'Recommendation',
      widthT: 100,
      editable: true,
    },
    {
      field: 'targetDate',
      title: 'Target Date',
      widthT: 100,
      editable: true,
      type: 'date',
    },
    { field: 'remark', title: 'Resp.', widthT: 100, editable: true },
    // { field: 'remarks', title: 'Remarks', widthT: 200, editable: true },
  ],
  majorPeopleInitiative: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No.',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'plant', title: 'Plant', widthT: 100, editable: false },
    {
      field: 'initiativeDescription',
      title: 'Initiative Description',
      widthT: 100,
      editable: true,
    },
    { field: 'outcome', title: 'Outcome', widthT: 100, editable: true },
    {
      field: 'recommendation',
      title: 'Recommendation',
      widthT: 100,
      editable: true,
    },
    {
      field: 'targetDate',
      title: 'Target Date',
      widthT: 100,
      editable: true,
      type: 'date',
    },
    { field: 'remark', title: 'Resp.', widthT: 100, editable: true },
    // { field: 'remarks', title: 'Remarks', widthT: 200, editable: true },
  ],
  production: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    { field: 'plant', title: 'Plant', widthT: 100, editable: false },
    { field: 'uom', title: 'UOM', widthT: 80, editable: false },
    {
      title: `FY ${AOP_YEAR}`,
      children: [
        {
          field: 'aop',
          title: `FY ${AOP_YEAR} AOP`,
          widthT: 100,
          editable: true,
          type: 'number',
        },
        {
          field: 'basis',
          title: `Basis for AOP FY ${AOP_YEAR}`,
          widthT: 130,
          editable: true,
        },
      ],
    },
    { field: 'remarks', title: 'Remarks', editable: true, widthT: 100 },
  ],
  conversionVariableCost: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    { field: 'plant', title: 'Plant', editable: false },
    { field: 'costHead', title: 'Cost Head', editable: false },
    { field: 'fy26Aop', title: 'FY26 AOP', editable: true, type: 'number' },
    {
      field: 'fy26Actual',
      title: 'FY26 Actual',
      editable: true,
      type: 'number',
    },
    { field: 'fy27Aop', title: 'FY27 AOP', editable: true, type: 'number' },
    { field: 'rationalReasons', title: 'Rational/ Reasons', editable: true },
  ],
  energyPerformance: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    { field: 'plant', title: 'Plant', editable: false, widthT: 150 },
    { field: 'uom', title: 'UOM', editable: false, widthT: 150 },
    {
      field: 'aopValue',
      title: `FY${prev} AOP`,
      editable: true,
      type: 'number',
      widthT: 150,
    },
    {
      field: 'actualValue',
      title: `FY${prev} Actual`,
      editable: true,
      widthT: 150,
      type: 'number',
    },
    {
      field: 'planValue',
      title: `FY${next} AOP`,
      editable: true,
      type: 'number',
      widthT: 150,
    },
    { field: 'remark', title: 'Remark', editable: true, widthT: 200 },
  ],
  contribution: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    { field: 'plant', title: 'Plant', editable: false },
    {
      title: 'FY 26 AOP',
      children: [
        {
          field: 'fy26AopRsMt',
          title: 'Rs/ MT',
          editable: true,
          type: 'number',
        },
        {
          field: 'fy26AopRsCrs',
          title: 'Rs. Crs.',
          editable: true,
          type: 'number',
        },
      ],
    },
    {
      title: 'FY26 Actual',
      children: [
        {
          field: 'fy26ActualRsMt',
          title: 'Rs/ MT',
          editable: true,
          type: 'number',
        },
        {
          field: 'fy26ActualRsCrs',
          title: 'Rs. Crs.',
          editable: true,
          type: 'number',
        },
      ],
    },
    {
      title: 'FY27 AOP',
      children: [
        {
          field: 'fy27AopRsMt',
          title: 'Rs/ MT',
          editable: true,
          type: 'number',
        },
        {
          field: 'fy27AopRsCrs',
          title: 'Rs. Crs.',
          editable: true,
          type: 'number',
        },
      ],
    },
    { field: 'rationalReasons', title: 'Rationale/ Reasons', editable: true },
  ],
  majorProcessIncidentsFy26: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No.',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'plant', title: 'Plant', widthT: 100, editable: true },
    {
      field: 'incidentDescription',
      title: 'Incident Description',
      widthT: 100,
      editable: true,
    },
    {
      field: 'rootCause',
      title: 'Root Cause Analysis',
      widthT: 100,
      editable: true,
    },
    {
      field: 'recommendation',
      title: 'Recommendation',
      widthT: 100,
      editable: true,
    },
    {
      field: 'targetDate',
      title: 'Target Date',
      widthT: 120,
      editable: true,
      type: 'date',
    },
    { field: 'resp', title: 'Resp.', widthT: 100, editable: true },
  ],
  fixedExpenses: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'srNo',
      title: 'Sr. No.',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    {
      field: 'particulars',
      title: 'Particulars',
      widthT: 100,
      editable: false,
    },
    {
      title: 'FY',
      children: [
        {
          field: 'fy26Aop',
          title: 'AOP',
          widthT: 100,
          editable: true,
          type: 'number',
        },
        {
          field: 'fy26Actual',
          title: 'Actual',
          widthT: 100,
          editable: true,
          type: 'number',
        },
      ],
    },
    {
      title: 'AOP',
      children: [
        {
          field: 'fy27Aop',
          title: 'AOP',
          widthT: 100,
          editable: true,
          type: 'number',
        },
        {
          field: 'percentChange',
          title: '% Change',
          widthT: 80,
          editable: true,
          type: 'number',
        },
        {
          field: 'variance',
          title: 'Variance',
          widthT: 80,
          editable: true,
          type: 'number',
        },
      ],
    },
    { field: 'remarks', title: 'Remarks', widthT: 100, editable: true },
  ],
  capexPlan: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'proposal', title: 'Proposal', widthT: 150, editable: true },
    { field: 'category', title: 'Category', widthT: 150, editable: true },
    {
      field: 'justification',
      title: 'Justification',
      widthT: 150,
      editable: true,
    },
    {
      field: 'cost',
      title: 'Cost (Rs Cr)',
      widthT: 100,
      editable: true,
      type: 'number',
    },
    {
      field: 'benefit',
      title: 'Benefit (Rs Cr)',
      widthT: 100,
      editable: true,
      type: 'number',
    },
    { field: 'target', title: 'Target', widthT: 100, editable: true },
    { field: 'status', title: 'Status', widthT: 100, editable: true },
  ],
  productionTph: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'plant', title: 'Plant', widthT: 150, editable: true },
    { field: 'tph', title: 'TPH', widthT: 150, editable: true, type: 'number' },
    {
      field: 'fy26Aop',
      title: 'FY26 AOP',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'fy26Actual',
      title: 'FY26 Actual',
      widthT: 100,
      editable: true,
      type: 'number',
    },
    {
      field: 'fy27Aop',
      title: 'FY27 AOP',
      widthT: 100,
      editable: true,
      type: 'number',
    },
    {
      field: 'rationalReasons',
      title: 'Rationale/ Reasons',
      widthT: 170,
      editable: true,
    },
  ],
  shutdownSlowdown: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'plant', title: 'Plant', widthT: 150, editable: true },
    {
      field: 'sdDays',
      title: 'No of S/D days',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'slowdownDays',
      title: 'No of slowdown days',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'monthly',
      title: 'Month',
      type: 'monthDropdownPEPP',
      widthT: 150,
      editable: true,
    },
    { field: 'sdPlan', title: 'S/D Plan', widthT: 150, editable: true },
  ],
  technicalAvailability: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'plant', title: 'Plant', widthT: 150, editable: true },
    {
      field: 'fy26Aop',
      title: 'FY26 AOP',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'fy26Actual',
      title: 'FY26 Actual',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'fy27Aop',
      title: 'FY27 AOP',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'rationalReasons',
      title: 'Rationale/ Reasons',
      widthT: 200,
      editable: true,
    },
  ],
  mcuCapacityUtilization: [
    { field: 'id', title: 'ID', editable: false, hidden: true },
    {
      field: 'sno',
      title: 'S.No',
      widthT: 60,
      editable: false,
      align: 'right',
      format: '{0:0}',
    },
    { field: 'plant', title: 'Plant', widthT: 150, editable: true },
    {
      field: 'fy26Aop',
      title: 'FY26 AOP',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'fy26Actual',
      title: 'FY26 Actual',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'fy27Aop',
      title: 'FY27 AOP',
      widthT: 150,
      editable: true,
      type: 'number',
    },
    {
      field: 'rationalReasons',
      title: 'Rationale/ Reasons',
      widthT: 200,
      editable: true,
    },
  ],
})

export default getSiteAOPReportColumns
