name: wks-platform
services:

    camunda:
        image: ${CAMUNDA_DOCKER_IMAGE}:${CAMUNDA7_VERSION}
        command: ./camunda.sh --rest --webapps
        ports:
            - 8080:8080
            - 8089:8089
        healthcheck:
            test: curl --fail http://localhost:8080/engine-rest/version || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        depends_on:
            mongodb:
                condition: service_healthy

    case-engine-rest-api:
        build:
            context: apps/java/services/case-engine-rest-api
        ports:
            - 8081:8081
        links:
            - mongodb
            - camunda
            - openldap
        env_file:
            - case-engine-rest-api.env
        environment:
            - CAMUNDA_VERSION=camunda7
            - CAMUNDA_BASE_URL=${CAMUNDA_BASE_URL}
            - MONGO_DATABASE=${MONGO_WKS_DATABASE}
            - MONGO_DATABASE_TENANT=${MONGO_DEMO_DATA_LOADER_DATABASE}
            - MONGO_CONN=${MONGO_CONNECTION_URL}
            - KEYCLOAK_URL=${KEYCLOAK_URL}
            - OPA_URL=${OPA_URL}
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy
#            openldap:
#                condition: service_healthy  # Ensure OpenLDAP is healthy before connecting
#        networks:
#            - ldap_network  # Add this to match OpenLDAP's network
      
      
    c7-external-tasks:
        build:
            context: apps/java/services/c7-external-tasks
        links:
            - camunda
            - case-engine-rest-api
        environment:
            - CAMUNDA_BASE_URL=${CAMUNDA_BASE_URL}
            - CAMUNDA_USERNAME=${CAMUNDA_USERNAME}
            - CAMUNDA_PASSWORD=${CAMUNDA_PASSWORD}
            - KEYCLOAK_URL=${KEYCLOAK_TOKEN_URL}
            - WKS_CASE_API_URL=${WKS_CASE_API_URL}
            - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
            - DISABLE_BACKOFF_STRATEGY=${DISABLE_BACKOFF_STRATEGY}
        depends_on:
            camunda:
                condition: service_healthy

    openldap:
        image: osixia/openldap:latest
        container_name: my-openldap-container
        ports:
            - "389:389"  # Exposing LDAP port
            - "636:636"  # Exposing LDAPS port (if needed)
        environment:
            - LDAP_ORGANISATION=Example Corp
            - LDAP_DOMAIN=example.com
            - LDAP_ADMIN_PASSWORD=admin
#        restart: unless-stopped  # Restart the container unless stopped manually
#        networks:
#            - ldap_network  # Custom network for better isolation if needed

#networks:
#  ldap_network:
#    driver: bridge  # Custom bridge network for your containers