

services:

  novu-publisher:
    build:
      context: apps/node/novu-publisher
    environment:
        - LOG_LEVEL=${NOVU_LOG_LEVEL}
        - KAFKA_URL=${KAFKA_URL}
        - NOVU_TRIGGER_URL=${NOVU_TRIGGER_URL}
        - NOVU_API_KEY=${NOVU_API_KEY}
        - NOVU_APP_ID=${NOVU_APP_ID}
        - NOVU_CASE_CREATE_WORKFLOW=${KAFKA_TOPIC_CASE_CREATE}
        - NOVU_HUMAN_TASK_CREATE_WORKFLOW=${KAFKA_TOPIC_CREATE_HUMAN_TASK}
    depends_on:
      - kafka
      - zookeeper
    ports:
        - 3002:3002
                    