

services:
  websocket-publisher:
    build:
      context: apps/node/websocket-publisher
    ports:
      - "8484:8484"
    environment:
        - LOG_LEVEL=${WEBSOCKET_LOG_LEVEL}
        - WEBSOCKET_PORT=8484
        - KAFKA_URL=${KAFKA_URL}
    depends_on:
      - kafka
      - zookeeper