#Enable SPNEGO authentication
spi-authenticator-spnego-required=true;
 
#Set the HTTP authentication mechanisms
http-enabled=true
http-auth-mechanism=SPNEGO,BASIC
 
#Specify the Kerberos keytab and principal
spi-authenticator-spnego-keytab=/opt/keycloak/data/keycloak.keytab
spi-authenticator-spnego-principal=HTTP/apm-cm-exxonmobil-useast.connectedplant.honeywell.com@CONNECTEDPLANT.HONEYWELL.COM
 
#Allow delegation
spi-authenticator-spnego-allow-delegation=true
 
#Enable debug logging for troubleshooting
log-level=org.keycloak.authentication.authenticators.browser.SpnegoAuthenticator:DEBUG
