[libdefaults]
    default_realm = DEV.CONNECTEDPLANT.HONEYWELL.COM
    dns_lookup_realm = false
    dns_lookup_kdc = true
    forwardable = true
    proxiable = true

[realms]
    DEV.CONNECTEDPLANT.HONEYWELL.COM = {
        kdc = kdc.dev.connectedplant.honeywell.com:88
        admin_server = kdc.dev.connectedplant.honeywell.com:749
        default_domain = connectedplant.honeywell.com
    }

[domain_realm]
    .connectedplant.honeywell.com = DEV.CONNECTEDPLANT.HONEYWELL.COM
    connectedplant.honeywell.com = DEV.CONNECTEDPLANT.HONEYWELL.COM

[logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/kdc.log
    admin_server = FILE:/var/log/kadmind.log
