[libdefaults]
    default_realm = DEV.CONNECTEDPLANT.HONEYWELL.COM
    dns_lookup_realm = false
    dns_lookup_kdc = true
    forwardable = true
    proxiable = true
    default_tkt_enctypes = aes256-cts-hmac-sha1-96
    default_tgs_enctypes = aes256-cts-hmac-sha1-96
    permitted_enctypes = aes256-cts-hmac-sha1-96

[realms]
    DEV.CONNECTEDPLANT.HONEYWELL.COM = {
        kdc = uswestadds02.dev.connectedplant.honeywell.com
        kdc = uswestadds01.dev.connectedplant.honeywell.com
        admin_server = uswestadds02.dev.connectedplant.honeywell.com
    }

[domain_realm]
    .connectedplant.honeywell.com = DEV.CONNECTEDPLANT.HONEYWELL.COM
    connectedplant.honeywell.com = DEV.CONNECTEDPLANT.HONEYWELL.COM

[logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/kdc.log
    admin_server = FILE:/var/log/kadmind.log
