export const MockPlantShutdownSlowdownAPI = {
  async getReport({ valueFormat }) {
    return {
      columns: [
        {
          field: 'sno',
          title: 'Sl no',
          widthT: 58,
          editable: false,
          align: 'right',
          type: 'number',
          format: '{0:0}',
        },
        {
          field: 'criticalActivity',
          title: 'Critical Routine Activity',
          widthT: 120,
          editable: false,
        },
        {
          title: 'Best achieved at site in the last 4 years',
          children: [
            {
              field: 'bestAchievedSiteFreq',
              title: 'Frequency',
              widthT: 120,
              editable: false,
              type: 'number',
              format: valueFormat,
            },
            {
              field: 'bestAchievedSiteDur',
              title: 'Duration',
              widthT: 120,
              editable: false,
              type: 'number',
              format: valueFormat,
            },
          ],
        },
        {
          title: 'Best achieved in the group',
          children: [
            {
              field: 'bestAchievedGroupFreq',
              title: 'Frequency',
              widthT: 120,
              editable: false,
              type: 'number',
              format: valueFormat,
            },
            {
              field: 'bestAchievedGroupDur',
              title: 'Duration',
              widthT: 120,
              editable: false,
              type: 'number',
              format: valueFormat,
            },
          ],
        },
        {
          title: 'Actual 2024-25',
          children: [
            {
              field: 'actualPrevYearFreq',
              title: 'Frequency',
              widthT: 120,
              editable: false,
              type: 'number',
              format: valueFormat,
            },
            {
              field: 'actualPrevYearDur',
              title: 'Duration',
              widthT: 120,
              editable: false,
              type: 'number',
              format: valueFormat,
            },
          ],
        },
        {
          title: 'Budget 2025-26',
          children: [
            {
              field: 'budgetNextYearFreq',
              title: 'Frequency',
              widthT: 150,
              editable: false,
              type: 'number',
              format: valueFormat,
            },
            {
              field: 'budgetNextYearDur',
              title: 'Duration',
              widthT: 150,
              editable: false,
              type: 'number',
              format: valueFormat,
            },
          ],
        },
        {
          field: 'clubbedActivities',
          title: 'Activities that can be clubbed with the critical activity',
          widthT: 150,
          editable: false,
        },
        {
          field: 'explanationNotBest',
          title:
            'Explanation for not proposing the best achieved frequency / duration',
          widthT: 150,
          editable: false,
        },
        {
          field: 'throughputReduction',
          title: 'Throughput reduction during the period',
          widthT: 150,
          type: 'number',
          editable: false,
        },
        {
          field: 'lossRecoverable',
          title: 'Is the production Loss recoverable',
          widthT: 150,
          editable: false,
        },
      ],
      data: [
        {
          id: 1,
          sno: 1,
          criticalActivity: 'Example Critical Activity 1',
          bestAchievedSiteFreq: 1,
          bestAchievedSiteDur: 24,
          bestAchievedGroupFreq: 1,
          bestAchievedGroupDur: 20,
          actualPrevYearFreq: 1,
          actualPrevYearDur: 26,
          budgetNextYearFreq: 1,
          budgetNextYearDur: 24,
          clubbedActivities: 'None',
          explanationNotBest: 'Standard procedure',
          throughputReduction: '10%',
          lossRecoverable: 'Yes',
          isEditable: false,
        },
        {
          id: 2,
          sno: 2,
          criticalActivity: 'Example Critical Activity 2',
          bestAchievedSiteFreq: 2,
          bestAchievedSiteDur: 12,
          bestAchievedGroupFreq: 2,
          bestAchievedGroupDur: 10,
          actualPrevYearFreq: 2,
          actualPrevYearDur: 14,
          budgetNextYearFreq: 2,
          budgetNextYearDur: 12,
          clubbedActivities: 'Activity 3',
          explanationNotBest: 'Optimized',
          throughputReduction: '5%',
          lossRecoverable: 'No',
          isEditable: false,
        },
      ],
    }
  },
}
