export const MockMonthwiseOperatingHoursAPI = {
  async getReport({ AOP_YEAR, valueFormat }) {
    return {
      columns: [
        {
          field: 'Month',
          title: 'Month',
          widthT: 120,
          editable: false,
        },
        {
          field: 'TotalAvailableHrs',
          title: 'Total available Hrs',
          widthT: 150,
          editable: false,
          type: 'number',
          format: valueFormat,
        },
        {
          field: 'PlannedTurnaroundHrs',
          title: 'Planned Turnaround Hrs',
          widthT: 180,
          editable: true,
          type: 'number',
          format: valueFormat,
        },
        {
          field: 'PlannedShutdownOtherThanTurnaroundHrs',
          title: 'Planned shutdown other than Turnaround Hrs',
          widthT: 250,
          editable: true,
          type: 'number',
          format: valueFormat,
        },
        {
          field: 'RoutineShutdownHrs',
          title: 'Routine shutdown Hrs',
          widthT: 180,
          editable: true,
          type: 'number',
          format: valueFormat,
        },
        {
          field: 'SlowdownHrs',
          title: 'Slowdown Hrs',
          widthT: 150,
          editable: true,
          type: 'number',
          format: valueFormat,
        },
        {
          field: 'NetOperatingHours',
          title: 'Net operating Hours',
          widthT: 180,
          editable: false,
          type: 'number',
          format: valueFormat,
        },
        {
          field: 'Remark',
          title: 'Remarks',
          widthT: 200,
          editable: true,
        },
      ],
      data: [
        {
          id: 0,
          Month: 'April',
          TotalAvailableHrs: 720,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 16,
          SlowdownHrs: 8,
          NetOperatingHours: 704,
          Remark: '',
        },
        {
          id: 1,
          Month: 'May',
          TotalAvailableHrs: 744,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 0,
          NetOperatingHours: 744,
          Remark: '',
        },
        {
          id: 2,
          Month: 'June',
          TotalAvailableHrs: 720,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 0,
          NetOperatingHours: 720,
          Remark: '',
        },
        {
          id: 3,
          Month: 'July',
          TotalAvailableHrs: 744,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 0,
          NetOperatingHours: 744,
          Remark: '',
        },
        {
          id: 4,
          Month: 'August',
          TotalAvailableHrs: 744,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 192,
          NetOperatingHours: 744,
          Remark: '',
        },
        {
          id: 5,
          Month: 'September',
          TotalAvailableHrs: 720,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 360,
          NetOperatingHours: 720,
          Remark: '',
        },
        {
          id: 6,
          Month: 'October',
          TotalAvailableHrs: 744,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 96,
          NetOperatingHours: 744,
          Remark: '',
        },
        {
          id: 7,
          Month: 'November',
          TotalAvailableHrs: 720,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 336,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 144,
          NetOperatingHours: 384,
          Remark: '',
        },
        {
          id: 8,
          Month: 'December',
          TotalAvailableHrs: 744,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 0,
          NetOperatingHours: 744,
          Remark: '',
        },
        {
          id: 9,
          Month: 'January',
          TotalAvailableHrs: 744,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 0,
          NetOperatingHours: 744,
          Remark: '',
        },
        {
          id: 10,
          Month: 'February',
          TotalAvailableHrs: 672,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 0,
          NetOperatingHours: 672,
          Remark: '',
        },
        {
          id: 11,
          Month: 'March',
          TotalAvailableHrs: 744,
          PlannedTurnaroundHrs: 0,
          PlannedShutdownOtherThanTurnaroundHrs: 0,
          RoutineShutdownHrs: 0,
          SlowdownHrs: 0,
          NetOperatingHours: 744,
          Remark: '',
        },
      ],
    }
  },
}
