server:
   port: 8081
   servlet:
      context-path: /cm

logging:
   level:
      root: INFO
      com.wks: INFO
      com.wks.api.security: DEBUG
      com.wks.caseengine: DEBUG
      com.wks.caseengine.command: INFO
      com.wks.caseengine.pagination: INFO
      org.springframework.web.client.RestTemplate: INFO
      org.springframework.security: INFO
      org.apache.http: INFO
      httpclient.wire: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.mail: DEBUG



spring.mvc.converters.preferred-json-mapper: gson

wks.bpm.engine.camunda.version: ${CAMUNDA_VERSION:camunda7}

camunda.bpm.client.base-url: ${CAMUNDA_BASE_URL:http://localhost:8080/engine-rest}

zeebe.client.broker.gateway-address: ${CAMUNDA8_ZEEBE_GATEWAY_ADDRESS:127.0.0.1:26500}
zeebe.client.security.plaintext: true
camunda.operate.client.enabled: true
camunda.operate.client.url: ${CAMUNDA8_OPERATE_URL:http://localhost:8281}
camunda.operate.client.username: ${CAMUNDA8_OPERATE_USERNAME:demo}
camunda.operate.client.password: ${CAMUNDA8_OPERATE_PASSWORD:demo}

camunda.tasklist.client.url: ${CAMUNDA8_TASKLIST_URL:http://localhost:8182}
camunda.tasklist.client.username: ${CAMUNDA8_TASKLIST_USERNAME:demo}
camunda.tasklist.client.password: ${CAMUNDA8_TASKLIST_PASSWORD:demo}

spring.data.mongodb.uri: ${MONGO_CONN:mongodb://localhost}
spring.data.mongodb.database: ${MONGO_DATABASE:shared}
spring.data.mongodb.database.tenant: ${MONGO_DATABASE_TENANT:localhost}
spring.data.mongodb.database.min-pool-size: 0
spring.data.mongodb.database.max-pool-size: 5
spring.data.mongodb.database.max-connection-idle-time: 3000
spring.data.mongodb.database.max-connection-life-time: 3000

opa.url: ${OPA_URL:http://localhost:8181/v1/data/wks/authz/allow}
keycloak.url: ${KEYCLOAK_URL:http://localhost:8082/cm}
keycloak.realm: ${KEYCLOAK_REALM:localhost}
keycloak.client-id: ${KEYCLOAK_CLIENT_ID:wks-portal}
keycloak.username: ${KEYCLOAK_ADMIN:admin}
keycloak.password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
keycloak.admin-url: ${KEYCLOAK_ADMIN_URL:http://localhost:8082/cm}
keycloak.idp-alias: ${KEYCLOAK_IDP_ALIAS:oidc}
ge.authentication.datasource: ${GE_AUTHENTICATION_DATASOURCE}
ge.authentication.id: ${GE_AUTHENTICATION_ID}
ge.authentication.password: ${GE_AUTHENTICATION_PASSWORD}
ge.authentication.api: ${GE_AUTHENTICATION_API}
ge.users.api: ${GE_USERS_API}
ge.create_case.api: ${GE_CREATE_CASE_API}
ge.case_statue.api: ${GE_CASE_STATUS_API}

management.health.mongo.enabled: false
management.health.reds.enabled: false

spring:
  datasource:
    # Configuration for Database 1
    db1:
      #url: jdbc:sqlserver://216.48.180.83;databaseName=case_management;trustServerCertificate=true
      #username: sa
      #password: "#Qwer123"
      url: ${SQL_SERVER_1_URL:jdbc:sqlserver://216.48.180.83;databaseName=case_management;trustServerCertificate=true;portNumber=1433}
      username: ${SQL_SERVER_1_USERNAME:sa}
      password: ${SQL_SERVER_1_PASSWORD:"#Qwer123"}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      name: ${SQL_SERVER_1}
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 300000
        max-lifetime: 250000     
        validation-timeout: 5000
        connection-test-query: SELECT 1

    # Configuration for Database 2
    db2:
      #url: jdbc:sqlserver://216.48.180.83;databaseName=CaseManagement;trustServerCertificate=true
      #username: sa
      #password: "#Qwer123"
      url: ${SQL_SERVER_2_URL:jdbc:sqlserver://216.48.180.83;databaseName=CaseManagement;trustServerCertificate=true;portNumber=1433}
      username: ${SQL_SERVER_2_USERNAME:sa}
      password: ${SQL_SERVER_2_PASSWORD:"#Qwer123"}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 300000
        max-lifetime: 250000      
        validation-timeout: 5000
        connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  
  mail:
    # host: smtp.gmail.com
    # port: 587
    # username: shrikant.mnt@gmail.com
    # password: "ldaortwzpbjadvez"
    # fromEmail: shrikant.mnt@gmail.com

    # host: smtp.honeywell.com
    # port: 25
    # fromEmail:  smtp@honeywell.com

    # host: smtp-secure.honeywell.com
    # port: 587
    # fromEmail: apm-cm-notifications@honeywell.com

    host: ${SMTP_HOST:smtp-secure.honeywell.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    fromEmail: ${SMTP_FROM_EMAIL}
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      debug: true

  ldap:
    # url: ldap://your-ad-server:389
    # base-dn: DC=example,DC=com
    # username: your-bind-user@example.com
    # password: your-bind-password
    url: ldap://my-openldap-container:389
    base-dn: dc=example,dc=com
    username: cn=admin,dc=example,dc=com
    password: admin
    
ldap:
  search:
    base: ou=users,dc=example,dc=com
    filter: "(objectClass=user)"


management.endpoints.web.exposure.include: health,info, metrics,db
management.endpoint.health.show-details: never

case.engine.case-creation-process: case-instance-create
case.engine.email-to-case-process: email-to-case
case.engine.email-to-case-outbound-process: email-to-case-outbound

case.engine.actuator.enabled: true
case.engine.swagger.enabled: true

wks.kafka.enabled: ${KAFKA_ENABLED:false}
wks.kafka.topic.case-create: ${KAFKA_TOPIC_CASE_CREATE:case-create}
wks.kafka.topic.case-email-outbound: ${KAFKA_TOPIC_CASE_EMAIL_OUTBOUND:case-email-outbound}
spring.kafka.bootstrap-servers: ${KAFKA_URL:localhost:9092}

react.frontend.url: ${REACT_FRONTEND_URL:http://localhost:3001/cm}

# SSO iframe integration
sso.allowed-origin: ${APM_ORIGIN:http://localhost:3000}
