package com.wks.caseengine.cpp.dto;

public interface PlantFuelAvailabilityMonthlyProjection {
    String getId();
    String getPlantName();
    String getPlantFkId();
    // April
    String getAprFuelFkId();
    String getAprFuelName();
    Integer getAprPriority();
    Double getAprQuantity();
    // May
    String getMayFuelFkId();
    String getMayFuelName();
    Integer getMayPriority();
    Double getMayQuantity();
    // June
    String getJunFuelFkId();
    String getJunFuelName();
    Integer getJunPriority();
    Double getJunQuantity();
    // July
    String getJulFuelFkId();
    String getJulFuelName();
    Integer getJulPriority();
    Double getJulQuantity();
    // August
    String getAugFuelFkId();
    String getAugFuelName();
    Integer getAugPriority();
    Double getAugQuantity();
    // September
    String getSepFuelFkId();
    String getSepFuelName();
    Integer getSepPriority();
    Double getSepQuantity();
    // October
    String getOctFuelFkId();
    String getOctFuelName();
    Integer getOctPriority();
    Double getOctQuantity();
    // November
    String getNovFuelFkId();
    String getNovFuelName();
    Integer getNovPriority();
    Double getNovQuantity();
    // December
    String getDecFuelFkId();
    String getDecFuelName();
    Integer getDecPriority();
    Double getDecQuantity();
    // January
    String getJanFuelFkId();
    String getJanFuelName();
    Integer getJanPriority();
    Double getJanQuantity();
    // February
    String getFebFuelFkId();
    String getFebFuelName();
    Integer getFebPriority();
    Double getFebQuantity();
    // March
    String getMarFuelFkId();
    String getMarFuelName();
    Integer getMarPriority();
    Double getMarQuantity();
    // Common
    String getRemarks();
    String getAopYear();
}
